# Generated by Django 4.1.3 on 2022-12-15 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_column="接口地址",
                        db_index=True,
                        help_text="接口地址",
                        max_length=500,
                        verbose_name="接口地址",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_column="唯一标识",
                        db_index=True,
                        help_text="唯一标识",
                        max_length=100,
                        unique=True,
                        verbose_name="唯一标识",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="爬取源",
                        help_text="爬取源",
                        max_length=20,
                        verbose_name="爬取源",
                    ),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        db_column="爬取时间", help_text="爬取时间", verbose_name="爬取时间"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        db_column="描述",
                        default="",
                        help_text="描述",
                        max_length=500,
                        verbose_name="描述",
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        db_column="内容摘要",
                        help_text="内容摘要",
                        max_length=200,
                        verbose_name="内容摘要",
                    ),
                ),
                (
                    "err_msg",
                    models.CharField(
                        blank=True,
                        db_column="错误信息",
                        default="",
                        help_text="错误信息",
                        max_length=500,
                        verbose_name="错误信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "API",
                "verbose_name_plural": "API",
                "db_table": "API",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="关键字",
                        db_index=True,
                        default="",
                        help_text="关键字",
                        max_length=50,
                        unique=True,
                        verbose_name="关键字",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        db_column="创建时间",
                        default=datetime.datetime.now,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "关键字",
                "verbose_name_plural": "关键字",
                "db_table": "关键字",
                "ordering": ["create_time"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_column="页面地址",
                        db_index=True,
                        help_text="页面地址",
                        max_length=500,
                        verbose_name="页面地址",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_column="唯一标识",
                        db_index=True,
                        help_text="唯一标识",
                        max_length=100,
                        unique=True,
                        verbose_name="唯一标识",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "待爬取"), (1, "爬取中"), (2, "已爬取"), (3, "爬取错误")],
                        db_column="状态",
                        default=0,
                        help_text="状态",
                        verbose_name="状态",
                    ),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        db_column="爬取时间", help_text="爬取时间", verbose_name="爬取时间"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="爬取源",
                        help_text="爬取源",
                        max_length=20,
                        verbose_name="爬取源",
                    ),
                ),
                (
                    "deep",
                    models.IntegerField(
                        choices=[(1, "第一层"), (2, "第二层"), (3, "第三层")],
                        db_column="爬取深度",
                        default=1,
                        help_text="爬取深度",
                        verbose_name="爬取深度",
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        db_column="描述",
                        default="",
                        help_text="描述",
                        max_length=500,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "err_msg",
                    models.CharField(
                        blank=True,
                        db_column="错误信息",
                        default="",
                        help_text="错误信息",
                        max_length=500,
                        null=True,
                        verbose_name="错误信息",
                    ),
                ),
                (
                    "api",
                    models.ForeignKey(
                        blank=True,
                        db_column="api",
                        help_text="api",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page_server.api",
                        verbose_name="api",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        db_column="关键字",
                        help_text="关键字",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page_server.keyword",
                        verbose_name="关键字",
                    ),
                ),
            ],
            options={
                "verbose_name": "页面",
                "verbose_name_plural": "页面",
                "db_table": "页面",
                "ordering": ["-crawl_time"],
            },
        ),
        migrations.AddField(
            model_name="api",
            name="keyword",
            field=models.ForeignKey(
                db_column="关键字",
                help_text="关键字",
                on_delete=django.db.models.deletion.CASCADE,
                to="page_server.keyword",
                verbose_name="关键字",
            ),
        ),
    ]
