# Generated by Django 4.1.3 on 2022-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['create_time'], 'verbose_name': '关键字', 'verbose_name_plural': '关键字'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': [], 'verbose_name': '页面', 'verbose_name_plural': '页面'},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='create_time',
            field=models.DateTimeField(db_column='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(db_column='关键字', max_length=50, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='page',
            name='crawl_time',
            field=models.DateTimeField(db_column='爬取时间', verbose_name='爬取时间'),
        ),
        migrations.AlterModelTable(
            name='keyword',
            table='关键字',
        ),
        migrations.AlterModelTable(
            name='page',
            table='页面',
        ),
    ]
