# Generated by Django 4.2.3 on 2023-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='create_time',
            field=models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
