# Generated by Django 4.1.3 on 2022-12-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0002_alter_page_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="img_count",
        ),
    ]
