# Generated by Django 4.1.3 on 2022-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_server', '0002_alter_keyword_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(0, '待爬取'), (1, '已爬取')], db_column='状态', default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='page',
            name='uid',
            field=models.CharField(db_column='唯一标识', max_length=100, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(db_column='页面地址', verbose_name='页面地址'),
        ),
    ]
