# Generated by Django 4.1.3 on 2022-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0003_remove_page_img_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(
                db_column="页面地址",
                db_index=True,
                help_text="页面地址",
                max_length=500,
                verbose_name="页面地址",
            ),
        ),
    ]
