# Generated by Django 4.1.3 on 2022-11-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_server', '0003_alter_page_status_alter_page_uid_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='keyword',
            field=models.ForeignKey(db_column='关键字', on_delete=django.db.models.deletion.CASCADE, to='page_server.keyword', verbose_name='关键字'),
        ),
    ]
