# Generated by Django 4.1.3 on 2022-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0004_alter_page_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="img_count",
            field=models.IntegerField(
                db_column="抽到的图片", default=0, verbose_name="抽到的图片"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.IntegerField(
                choices=[(0, "待爬取"), (1, "爬取中"), (2, "已爬取")],
                db_column="状态",
                default=0,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="uid",
            field=models.CharField(
                db_column="唯一标识", db_index=True, max_length=100, verbose_name="唯一标识"
            ),
        ),
    ]
