# Generated by Django 4.1.3 on 2022-12-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0004_alter_page_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="desc",
            field=models.CharField(
                db_column="描述",
                default="",
                help_text="描述",
                max_length=500,
                verbose_name="描述",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="err_msg",
            field=models.CharField(
                db_column="错误信息",
                default="",
                help_text="错误信息",
                max_length=200,
                verbose_name="错误信息",
            ),
        ),
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_column="页面地址",
                        db_index=True,
                        help_text="页面地址",
                        max_length=500,
                        verbose_name="页面地址",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_column="唯一标识",
                        db_index=True,
                        help_text="唯一标识",
                        max_length=100,
                        verbose_name="唯一标识",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="爬取源",
                        help_text="爬取源",
                        max_length=20,
                        verbose_name="爬取源",
                    ),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        db_column="爬取时间", help_text="爬取时间", verbose_name="爬取时间"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        db_column="描述",
                        default="",
                        help_text="描述",
                        max_length=500,
                        verbose_name="描述",
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        db_column="内容摘要",
                        help_text="内容摘要",
                        max_length=200,
                        verbose_name="内容摘要",
                    ),
                ),
                (
                    "err_msg",
                    models.CharField(
                        db_column="错误信息",
                        default="",
                        help_text="错误信息",
                        max_length=200,
                        verbose_name="错误信息",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        db_column="关键字",
                        help_text="关键字",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page_server.keyword",
                        verbose_name="关键字",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="page",
            name="api",
            field=models.ForeignKey(
                db_column="api",
                help_text="api",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="page_server.api",
                verbose_name="api",
            ),
        ),
    ]
