# Generated by Django 4.1.3 on 2022-12-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0004_alter_api_url_alter_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(
                db_column="页面地址",
                db_index=True,
                help_text="页面地址",
                max_length=600,
                verbose_name="页面地址",
            ),
        ),
    ]
