# Generated by Django 4.1.3 on 2022-12-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0005_page_desc_page_err_msg_api_page_api"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="api",
            options={"verbose_name": "API", "verbose_name_plural": "API"},
        ),
        migrations.AlterModelTable(
            name="api",
            table="API",
        ),
    ]
