# Generated by Django 4.1.3 on 2022-11-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0005_page_img_count_alter_page_status_alter_page_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="source",
            field=models.CharField(
                db_column="爬取源", default="", max_length=20, verbose_name="爬取源"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="page",
            name="img_count",
            field=models.IntegerField(
                db_column="页面上的图片", default=0, verbose_name="页面上的图片"
            ),
        ),
    ]
