# Generated by Django 4.1.3 on 2022-11-27 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0006_page_source_alter_page_img_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["-crawl_time"],
                "verbose_name": "页面",
                "verbose_name_plural": "页面",
            },
        ),
        migrations.AlterField(
            model_name="keyword",
            name="create_time",
            field=models.DateTimeField(
                db_column="创建时间", default=datetime.datetime.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="keyword",
            field=models.CharField(
                db_column="关键字",
                db_index=True,
                max_length=50,
                unique=True,
                verbose_name="关键字",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.IntegerField(
                choices=[(0, "待爬取"), (1, "爬取中"), (2, "已爬取"), (3, "爬取错误")],
                db_column="状态",
                default=0,
                verbose_name="状态",
            ),
        ),
    ]
