# Generated by Django 4.1.3 on 2022-11-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0007_alter_page_options_alter_keyword_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="deep",
            field=models.IntegerField(
                choices=[(1, "第一层"), (2, "第二层"), (3, "第三层")],
                db_column="爬取深度",
                default=1,
                verbose_name="爬取深度",
            ),
        ),
    ]
