# Generated by Django 4.1.3 on 2022-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0007_alter_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="uid",
            field=models.CharField(
                db_column="唯一标识",
                db_index=True,
                help_text="唯一标识",
                max_length=100,
                unique=True,
                verbose_name="唯一标识",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="uid",
            field=models.CharField(
                db_column="唯一标识",
                db_index=True,
                help_text="唯一标识",
                max_length=100,
                unique=True,
                verbose_name="唯一标识",
            ),
        ),
    ]
