# Generated by Django 4.1.3 on 2022-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0008_alter_api_uid_alter_page_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="err_msg",
            field=models.CharField(
                db_column="错误信息",
                default="",
                help_text="错误信息",
                max_length=500,
                verbose_name="错误信息",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="err_msg",
            field=models.CharField(
                db_column="错误信息",
                default="",
                help_text="错误信息",
                max_length=500,
                verbose_name="错误信息",
            ),
        ),
    ]
