# Generated by Django 4.1.3 on 2022-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0009_alter_api_url_alter_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="url",
            field=models.URLField(
                db_column="接口地址", help_text="接口地址", max_length=768, verbose_name="接口地址"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(
                db_column="页面地址", help_text="页面地址", max_length=768, verbose_name="页面地址"
            ),
        ),
    ]
