# Generated by Django 4.1.3 on 2022-11-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_server', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_column='图片地址', help_text='图片地址', verbose_name='图片地址')),
                ('thumb_url', models.URLField(db_column='缩略图地址', help_text='缩略图地址', verbose_name='缩略图地址')),
                ('uid', models.CharField(db_column='唯一标识', db_index=True, help_text='唯一标识', max_length=100, unique=True, verbose_name='唯一标识')),
                ('status', models.IntegerField(choices=[(0, '待爬取'), (1, '爬取中'), (2, '已爬取'), (3, '爬取错误')], db_column='状态', default=0, help_text='状态', verbose_name='状态')),
                ('crawl_time', models.DateTimeField(db_column='爬取时间', help_text='爬取时间', verbose_name='爬取时间')),
                ('desc', models.CharField(db_column='图片描述', help_text='图片描述', max_length=1000, verbose_name='图片描述')),
                ('qualify', models.IntegerField(choices=[(0, '合格'), (1, '不合格')], db_column='是否合格', default=1, help_text='是否合格', verbose_name='是否合格')),
                ('source', models.CharField(db_column='爬取源', help_text='爬取源', max_length=20, verbose_name='爬取源')),
                ('keyword', models.ForeignKey(db_column='关键字', help_text='关键字', on_delete=django.db.models.deletion.CASCADE, to='page_server.keyword', verbose_name='关键字')),
                ('page', models.ForeignKey(db_column='页面链接', help_text='页面链接', on_delete=django.db.models.deletion.CASCADE, to='page_server.page', verbose_name='页面链接')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': '图片',
                'ordering': [],
            },
        ),
    ]
