# Generated by Django 4.1.3 on 2022-11-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_server', '0002_alter_keyword_options_alter_page_options_and_more'),
        ('img_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'ordering': [], 'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterField(
            model_name='img',
            name='crawl_time',
            field=models.DateTimeField(db_column='爬取时间', verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='img',
            name='desc',
            field=models.CharField(db_column='图片描述', max_length=1000, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='img',
            name='keyword',
            field=models.ForeignKey(db_column='关键字', on_delete=django.db.models.deletion.CASCADE, to='page_server.keyword', verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='img',
            name='page_url',
            field=models.ForeignKey(db_column='页面链接', on_delete=django.db.models.deletion.CASCADE, to='page_server.page', verbose_name='页面链接'),
        ),
        migrations.AlterField(
            model_name='img',
            name='status',
            field=models.IntegerField(choices=[(0, '待爬取'), (1, '已爬取')], db_column='状态', default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='img',
            name='thumb_url',
            field=models.URLField(db_column='缩略图地址', verbose_name='缩略图地址'),
        ),
        migrations.AlterField(
            model_name='img',
            name='uid',
            field=models.CharField(db_column='唯一标识', max_length=100, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='img',
            name='url',
            field=models.URLField(db_column='图片地址', verbose_name='图片地址'),
        ),
        migrations.AlterModelTable(
            name='img',
            table='图片',
        ),
    ]
