# Generated by Django 4.1.3 on 2022-12-15 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="crawl_time",
            field=models.DateTimeField(
                db_column="爬取时间",
                default=datetime.datetime.now,
                help_text="爬取时间",
                verbose_name="爬取时间",
            ),
        ),
    ]
