# Generated by Django 4.1.3 on 2022-12-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0005_page_desc_page_err_msg_api_page_api"),
        ("img_server", "0002_alter_img_thumb_url_alter_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="img",
            name="api",
            field=models.ForeignKey(
                db_column="api",
                help_text="api",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="page_server.api",
                verbose_name="api",
            ),
        ),
        migrations.AddField(
            model_name="img",
            name="err_msg",
            field=models.CharField(
                db_column="错误信息",
                default="",
                help_text="错误信息",
                max_length=200,
                verbose_name="错误信息",
            ),
        ),
        migrations.AddField(
            model_name="img",
            name="file_type",
            field=models.IntegerField(
                choices=[(0, "图片"), (1, "视频")],
                db_column="文件类型",
                default=0,
                help_text="文件类型",
                verbose_name="文件类型",
            ),
        ),
    ]
