# Generated by Django 4.1.3 on 2022-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0002_alter_img_options_alter_img_crawl_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="status",
            field=models.IntegerField(
                choices=[(0, "待爬取"), (1, "爬取中"), (2, "已爬取")],
                db_column="状态",
                default=0,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="img",
            name="uid",
            field=models.CharField(
                db_column="唯一标识",
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="唯一标识",
            ),
        ),
    ]
