# Generated by Django 4.1.3 on 2022-12-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page_server", "0001_initial"),
        ("img_server", "0002_alter_img_crawl_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="page",
            field=models.ForeignKey(
                blank=True,
                db_column="页面链接",
                help_text="页面链接",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="page_server.page",
                verbose_name="页面链接",
            ),
        ),
    ]
