# Generated by Django 4.1.3 on 2022-11-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0003_alter_img_status_alter_img_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="img",
            name="source",
            field=models.CharField(
                db_column="爬取源", default="", max_length=20, verbose_name="爬取源"
            ),
            preserve_default=False,
        ),
    ]
