# Generated by Django 4.2.3 on 2023-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_server', '0003_alter_img_desc_alter_img_err_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='desc',
            field=models.CharField(default='', help_text='描述', max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='img',
            name='err_msg',
            field=models.CharField(default='', help_text='错误信息', max_length=500, null=True, verbose_name='错误信息'),
        ),
    ]
