# Generated by Django 4.1.3 on 2022-12-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0003_alter_img_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="download",
            field=models.IntegerField(
                choices=[(0, "未下载"), (1, "已下载"), (2, "下载中"), (3, "下载失败")],
                db_column="是否已下载",
                default=0,
                help_text="是否已下载",
                verbose_name="是否已下载",
            ),
        ),
    ]
