# Generated by Django 4.1.3 on 2022-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0006_img_qualify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="qualify",
            field=models.IntegerField(
                choices=[(0, "合格"), (1, "不合格")],
                db_column="是否合格",
                default=1,
                verbose_name="是否合格",
            ),
        ),
    ]
