# Generated by Django 4.1.3 on 2022-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0008_alter_img_thumb_url_alter_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="desc",
            field=models.CharField(
                blank=True,
                db_column="图片描述",
                default="",
                help_text="图片描述",
                max_length=768,
                null=True,
                verbose_name="图片描述",
            ),
        ),
    ]
