# Generated by Django 4.1.3 on 2022-12-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("img_server", "0009_alter_img_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="desc",
            field=models.CharField(
                blank=True,
                db_column="图片描述",
                default="",
                help_text="图片描述",
                max_length=1000,
                null=True,
                verbose_name="图片描述",
            ),
        ),
        migrations.AlterField(
            model_name="img",
            name="thumb_url",
            field=models.URLField(
                db_column="缩略图地址",
                help_text="缩略图地址",
                max_length=1000,
                verbose_name="缩略图地址",
            ),
        ),
        migrations.AlterField(
            model_name="img",
            name="url",
            field=models.URLField(
                db_column="图片地址", help_text="图片地址", max_length=1000, verbose_name="图片地址"
            ),
        ),
    ]
