# Generated by Django 4.2.3 on 2023-08-06 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='关键字', max_length=50, unique=True, verbose_name='关键字')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
                'db_table': '关键字',
                'ordering': ['create_time'],
            },
        ),
    ]
