# Generated by Django 4.2.3 on 2023-08-06 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keyword_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='地址', max_length=1000, verbose_name='地址')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('desc', models.CharField(default='', help_text='描述', max_length=500, null=True, verbose_name='描述')),
                ('err_msg', models.CharField(default='', help_text='错误信息', max_length=500, null=True, verbose_name='错误信息')),
                ('source', models.CharField(help_text='爬取源', max_length=20, verbose_name='爬取源')),
                ('uid', models.CharField(db_index=True, help_text='唯一标识', max_length=100, unique=True, verbose_name='唯一标识')),
                ('md5', models.CharField(db_column='内容摘要', help_text='内容摘要', max_length=200, verbose_name='内容摘要')),
                ('keyword', models.ForeignKey(help_text='关键字', on_delete=django.db.models.deletion.CASCADE, to='keyword_server.keyword', verbose_name='关键字')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'API',
                'db_table': 'API',
            },
        ),
    ]
