# Generated by Django 4.2.3 on 2023-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_alter_api_create_time_alter_api_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='desc',
            field=models.CharField(default='', help_text='描述', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='err_msg',
            field=models.CharField(default='', help_text='错误信息', max_length=500, verbose_name='错误信息'),
        ),
    ]
